# Generated by Django 3.2.9 on 2021-12-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbd_app', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('hotline_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbd_app.neighbourhood')),
            ],
        ),
    ]
