# Generated by Django 3.2.9 on 2021-12-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbd_app', '0004_socialamenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('business_description', models.TextField()),
                ('business_contact_No', models.IntegerField()),
                ('business_contact_email', models.EmailField(max_length=254)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbd_app.neighbourhood')),
            ],
        ),
    ]
