# Generated by Django 3.2.9 on 2022-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbd_app', '0006_generalposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialamenities',
            name='hotline_number',
            field=models.BigIntegerField(),
        ),
    ]
