# Generated by Django 3.2.9 on 2022-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbd_app', '0007_alter_socialamenities_hotline_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_contact_No',
            field=models.BigIntegerField(),
        ),
    ]
