# Generated by Django 3.2.9 on 2022-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbd_app', '0009_police_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalposts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
